# Generated by Django 4.1.1 on 2023-01-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="terms",
            field=models.BooleanField(
                default=True, verbose_name="Declaro conocer y aceptar"
            ),
            preserve_default=False,
        ),
    ]
