# Generated by Django 4.1.1 on 2023-01-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="paid_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
