# Generated by Django 4.1.1 on 2023-02-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customuser_paid_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricing", name="allowed_property", field=models.IntegerField(),
        ),
    ]
