# Generated by Django 4.1.1 on 2023-02-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_pricing_allowed_property"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscription", name="pricing",),
        migrations.RemoveField(model_name="subscription", name="user",),
        migrations.RemoveField(model_name="customuser", name="paid_until",),
        migrations.RemoveField(model_name="customuser", name="terms",),
        migrations.DeleteModel(name="Pricing",),
        migrations.DeleteModel(name="Subscription",),
    ]
