# Generated by Django 4.1.1 on 2023-02-24 02:46

import apps.properties.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Comuna")),
                ("location_slug", models.SlugField()),
            ],
            options={"verbose_name": "Commune", "verbose_name_plural": "Communes",},
        ),
        migrations.CreateModel(
            name="IpVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                ("ip", models.CharField(max_length=100)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="OperationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_property",
                    models.CharField(max_length=100, verbose_name="Tipo de Propiedad"),
                ),
                ("total", models.CharField(max_length=100, verbose_name="Total")),
                (
                    "commission_percentage",
                    models.PositiveIntegerField(
                        verbose_name="Porcentaje Comisión(Valor Entero)"
                    ),
                ),
                ("commission_value", models.PositiveIntegerField()),
                (
                    "is_commission_paid",
                    models.BooleanField(default=False, verbose_name="Comisión Pagada"),
                ),
            ],
            options={
                "verbose_name": "OperationHistory",
                "verbose_name_plural": "OperationsHistory",
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre o Razón Social"
                    ),
                ),
                ("rut", models.CharField(max_length=15, verbose_name="Rut")),
                ("phone1", models.CharField(max_length=9, verbose_name="Telefono 1")),
                (
                    "phone2",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="Telefono 2"
                    ),
                ),
                ("email", models.EmailField(max_length=150, verbose_name="Correo")),
            ],
            options={"verbose_name": "Owner", "verbose_name_plural": "Owners",},
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("de", "Departamento"),
                            ("ca", "Casa"),
                            ("of", "Oficina"),
                            ("lc", "Local Comercial"),
                            ("su", "Sitio Urbano"),
                            ("pa", "Parcela"),
                            ("in", "Industrial"),
                            ("bo", "Bodega"),
                        ],
                        max_length=2,
                        verbose_name="Tipo de Propiedad",
                    ),
                ),
                (
                    "publish_type",
                    models.CharField(
                        choices=[
                            ("", "Seleccione un tipo"),
                            ("ve", "Venta"),
                            ("ar", "Arriendo"),
                            ("at", "Arriendo Temporada"),
                            ("pe", "Permuta"),
                        ],
                        max_length=2,
                        verbose_name="Tipo de Operación",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Titulo(hasta 100 caracteres)"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "common_expenses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Gastos comunes"
                    ),
                ),
                (
                    "google_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ubicación en Google Maps"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="Video"),
                ),
                ("is_new", models.BooleanField(default=False, verbose_name="Nueva")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "street_address",
                    models.CharField(max_length=50, verbose_name="Calle"),
                ),
                (
                    "street_number",
                    models.CharField(max_length=50, verbose_name="Numero Calle"),
                ),
                (
                    "num_roll",
                    models.CharField(max_length=50, verbose_name="Numero de Rol(SII)"),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="properties.commune",
                        verbose_name="Comuna",
                    ),
                ),
            ],
            options={"verbose_name": "Property", "verbose_name_plural": "Properties",},
        ),
        migrations.CreateModel(
            name="Realtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                ("first_name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Apellido"),
                ),
                ("phone1", models.CharField(max_length=9, verbose_name="Telefono 1")),
                (
                    "phone2",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="Telefono 2"
                    ),
                ),
                ("email", models.EmailField(max_length=150, verbose_name="Correo")),
            ],
            options={"verbose_name": "Realtor", "verbose_name_plural": "Realtors",},
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Comuna")),
            ],
            options={"verbose_name": "Region", "verbose_name_plural": "Regions",},
        ),
        migrations.CreateModel(
            name="UrbanSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "land_surface",
                    models.PositiveIntegerField(verbose_name="Superficie terreno (m²)"),
                ),
                (
                    "num_cellars",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Bodegas/Recintos",
                    ),
                ),
                (
                    "num_lot",
                    models.CharField(max_length=20, verbose_name="Número de Lote"),
                ),
                ("sector", models.CharField(max_length=250, verbose_name="Sector")),
                (
                    "water_feasibility",
                    models.CharField(
                        choices=[("si", "Si"), ("no", "No")],
                        max_length=2,
                        verbose_name="Factibilidad Agua",
                    ),
                ),
                (
                    "electricity_feasibility",
                    models.CharField(
                        choices=[("si", "Si"), ("no", "No")],
                        max_length=2,
                        verbose_name="Factibilidad Electricidad",
                    ),
                ),
                (
                    "sewer_feasibility",
                    models.CharField(
                        choices=[("si", "Si"), ("no", "No")],
                        max_length=2,
                        verbose_name="Factibilidad Alcantarillado",
                    ),
                ),
                (
                    "gas_feasibility",
                    models.CharField(
                        choices=[("si", "Si"), ("no", "No")],
                        max_length=2,
                        verbose_name="Factibilidad Gas",
                    ),
                ),
                ("feasibility", models.TextField(verbose_name="Factibilidad")),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urban_sites",
                        to="properties.property",
                    ),
                ),
            ],
            options={"verbose_name": "UrbanSite", "verbose_name_plural": "UrbanSites",},
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "land_surface",
                    models.PositiveIntegerField(verbose_name="Superficie terreno (m²)"),
                ),
                (
                    "builded_surface",
                    models.PositiveIntegerField(
                        verbose_name="Superficie construida (m²)"
                    ),
                ),
                (
                    "num_bathrooms",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Baños",
                    ),
                ),
                (
                    "num_local",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de Local"
                    ),
                ),
                (
                    "builded_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año de Construcción"
                    ),
                ),
                (
                    "service",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Internet", "Internet"),
                            ("Luz", "Luz"),
                            ("Agua Potable", "Agua Potable"),
                            ("Alcantarillado", "Alcantarillado"),
                            ("Alarma", "Alarma"),
                            ("Telefono", "Telefono"),
                            ("TV Cable", "TV Cable"),
                            ("Chimenea", "Chimenea"),
                            ("Calefaccion", "Calefaccion"),
                            ("Aire Acondicionado", "Aire Acondicionado"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Servicios",
                    ),
                ),
                (
                    "kitchen",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Comedor Diario", "Comedor Diario"),
                            ("Cocina Equipada", "Cocina Equipada"),
                            ("Cocina Amoblada", "Cocina Amoblada"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Cocina",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="properties.property",
                    ),
                ),
            ],
            options={"verbose_name": "Shop", "verbose_name_plural": "Shops",},
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pu", "Publicado"), ("dr", "No Publicado")],
                        default="dr",
                        max_length=3,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("wa", "En espera"),
                            ("an", "No concretada"),
                            ("ve", "Vendida"),
                            ("pe", "Permutada"),
                            ("ar", "Arrendada"),
                            ("at", "Arrendada por temporada"),
                        ],
                        default="wa",
                        max_length=2,
                    ),
                ),
                (
                    "type_price",
                    models.CharField(
                        choices=[
                            ("", "Seleccione un tipo"),
                            ("uf", "UF"),
                            ("usd", "USD"),
                            ("clp", "CLP"),
                        ],
                        max_length=3,
                        verbose_name="Tipo Moneda",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(verbose_name="Precio Publicación"),
                ),
                (
                    "appraisal_value",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Valor Tasación"
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Porcentaje Comisión",
                    ),
                ),
                (
                    "commission_value",
                    models.PositiveIntegerField(verbose_name="Monto Comisión"),
                ),
                ("is_iva", models.BooleanField(default=False, verbose_name="IVA")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destacada"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications_owner",
                        to="properties.owner",
                        verbose_name="Propietario",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="properties.property",
                    ),
                ),
                (
                    "realtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications_realtor",
                        to="properties.realtor",
                        verbose_name="Agente",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "views",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="publication_ip_visitor",
                        to="properties.ipvisitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.properties.models.property_images_directory_path
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "PropertyImage",
                "verbose_name_plural": "PropertyImages",
            },
        ),
        migrations.CreateModel(
            name="PropertyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre Completo"),
                ),
                ("from_email", models.EmailField(max_length=50, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="Télefono(opcional)"
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_contacts",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "PropertyContact",
                "verbose_name_plural": "PropertyContacts",
            },
        ),
        migrations.AddField(
            model_name="property",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="properties.region",
                verbose_name="Región",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "land_surface",
                    models.PositiveIntegerField(verbose_name="Superficie terreno (m²)"),
                ),
                (
                    "num_cellars",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Bodegas/Recintos",
                    ),
                ),
                (
                    "num_lot",
                    models.CharField(max_length=20, verbose_name="Número de Lote"),
                ),
                ("sector", models.CharField(max_length=250, verbose_name="Sector")),
                (
                    "water_feasibility",
                    models.CharField(
                        choices=[("si", "Si"), ("no", "No")],
                        max_length=2,
                        verbose_name="Factibilidad Agua",
                    ),
                ),
                (
                    "electricity_feasibility",
                    models.CharField(
                        choices=[("si", "Si"), ("no", "No")],
                        max_length=2,
                        verbose_name="Factibilidad Electricidad",
                    ),
                ),
                (
                    "sewer_feasibility",
                    models.CharField(
                        choices=[("si", "Si"), ("no", "No")],
                        max_length=2,
                        verbose_name="Factibilidad Alcantarillado",
                    ),
                ),
                (
                    "gas_feasibility",
                    models.CharField(
                        choices=[("si", "Si"), ("no", "No")],
                        max_length=2,
                        verbose_name="Factibilidad Gas",
                    ),
                ),
                ("feasibility", models.TextField(verbose_name="Factibilidad")),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcels",
                        to="properties.property",
                    ),
                ),
            ],
            options={"verbose_name": "Parcel", "verbose_name_plural": "Parcels",},
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "land_surface",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Superficie terreno (m²)"
                    ),
                ),
                (
                    "builded_surface",
                    models.PositiveIntegerField(
                        verbose_name="Superficie construida (m²)"
                    ),
                ),
                (
                    "num_offices",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Oficinas",
                    ),
                ),
                (
                    "num_bathrooms",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Baños",
                    ),
                ),
                (
                    "num_parkings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Estacionamientos",
                    ),
                ),
                (
                    "num_cellars",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Bodegas/Recintos",
                    ),
                ),
                (
                    "num_floors",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Pisos",
                    ),
                ),
                (
                    "num_local",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de Local"
                    ),
                ),
                (
                    "builded_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año de Construcción"
                    ),
                ),
                (
                    "distribution",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Hall", "Hall"),
                            ("Patio de Servicio", "Patio de Servicio"),
                            ("Jardin", "Jardin"),
                            ("Sala Estar", "Sala Estar"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Espacios Adicionales",
                    ),
                ),
                (
                    "service",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Internet", "Internet"),
                            ("Luz", "Luz"),
                            ("Agua Potable", "Agua Potable"),
                            ("Alcantarillado", "Alcantarillado"),
                            ("Alarma", "Alarma"),
                            ("Telefono", "Telefono"),
                            ("Riego Automatico", "Riego Automatico"),
                            ("Porton Automatico", "Porton Automatico"),
                            ("Persianas Automaticas", "Persianas Automaticas"),
                            ("Calefaccion", "Calefaccion"),
                            ("Aire Acondicionado", "Aire Acondicionado"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Servicios",
                    ),
                ),
                (
                    "kitchen",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Comedor Diario", "Comedor Diario"),
                            ("Cocina Equipada", "Cocina Equipada"),
                            ("Cocina Amoblada", "Cocina Amoblada"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Cocina",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offices",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Office",
                "verbose_name_plural": "Offices",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Industrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "land_surface",
                    models.PositiveIntegerField(verbose_name="Superficie terreno (m²)"),
                ),
                (
                    "builded_surface",
                    models.PositiveIntegerField(
                        verbose_name="Superficie construida (m²)"
                    ),
                ),
                (
                    "num_cellars",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Bodegas",
                    ),
                ),
                (
                    "num_bathrooms",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Baños",
                    ),
                ),
                (
                    "num_offices",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Oficinas",
                    ),
                ),
                (
                    "num_local",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de Local"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industrials",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Industrial",
                "verbose_name_plural": "Industrials",
            },
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "land_surface",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Superficie terreno (m²)"
                    ),
                ),
                (
                    "builded_surface",
                    models.PositiveIntegerField(
                        verbose_name="Superficie construida (m²)"
                    ),
                ),
                (
                    "num_rooms",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Dormitorios",
                    ),
                ),
                (
                    "num_bathrooms",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Baños",
                    ),
                ),
                (
                    "num_parkings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Estacionamientos",
                    ),
                ),
                (
                    "num_cellars",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Bodegas",
                    ),
                ),
                (
                    "num_floors",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Selecione una opción"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Pisos",
                    ),
                ),
                (
                    "num_house",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número Casa"
                    ),
                ),
                (
                    "builded_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año de Construcción"
                    ),
                ),
                (
                    "distribution",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Baño Visita", "Baño Visita"),
                            ("Hall", "Hall"),
                            ("Antejardin", "Antejardin"),
                            ("Patio de Servicio", "Patio de Servicio"),
                            ("Estar de Servicio", "Estar de Servicio"),
                            ("Jardin", "Jardin"),
                            ("Despensa", "Despensa"),
                            ("Sala Estar", "Sala Estar"),
                            ("Quincho", "Quincho"),
                            ("Lavadero Interior", "Lavadero Interior"),
                            ("Lavadero Exterior", "Lavadero Exterior"),
                            ("Escritorio", "Escritorio"),
                            ("Mansarda", "Mansarda"),
                            ("Terraza", "Terraza"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Espacios Adicionales",
                    ),
                ),
                (
                    "service",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Internet", "Internet"),
                            ("Luz", "Luz"),
                            ("Agua Potable", "Agua Potable"),
                            ("Alcantarillado", "Alcantarillado"),
                            ("Alarma", "Alarma"),
                            ("Telefono", "Telefono"),
                            ("Riego Automatico", "Riego Automatico"),
                            ("Porton Automatico", "Porton Automatico"),
                            ("TV Cable", "TV Cable"),
                            ("Chimenea", "Chimenea"),
                            ("Calefaccion", "Calefaccion"),
                            ("Aire Acondicionado", "Aire Acondicionado"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Servicios",
                    ),
                ),
                (
                    "kitchen",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Comedor Diario", "Comedor Diario"),
                            ("Cocina Equipada", "Cocina Equipada"),
                            ("Cocina Amoblada", "Cocina Amoblada"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Cocina",
                    ),
                ),
                (
                    "other",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Persianas", "Persianas"),
                            ("Protecciones Ventana", "Protecciones Ventana"),
                            ("Termopaneles", "Termopaneles"),
                            ("Jacuzzi", "Jacuzzi"),
                            ("Piscina", "Piscina"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Otros",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="houses",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "House",
                "verbose_name_plural": "Houses",
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="commune",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communes",
                to="properties.region",
            ),
        ),
        migrations.CreateModel(
            name="Cellar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "land_surface",
                    models.PositiveIntegerField(verbose_name="Superficie terreno (m²)"),
                ),
                (
                    "builded_surface",
                    models.PositiveIntegerField(
                        verbose_name="Superficie construida (m²)"
                    ),
                ),
                (
                    "num_enclosures",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Recintos",
                    ),
                ),
                (
                    "num_bathrooms",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Baños",
                    ),
                ),
                (
                    "num_offices",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Oficinas",
                    ),
                ),
                (
                    "num_local",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de Local"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cellars",
                        to="properties.property",
                    ),
                ),
            ],
            options={"verbose_name": "Cellar", "verbose_name_plural": "Cellars",},
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "land_surface",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Superficie terreno (m²)"
                    ),
                ),
                (
                    "builded_surface",
                    models.PositiveIntegerField(
                        verbose_name="Superficie construida (m²)"
                    ),
                ),
                (
                    "num_rooms",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Dormitorios",
                    ),
                ),
                (
                    "num_bathrooms",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Baños",
                    ),
                ),
                (
                    "num_parkings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Estacionamientos",
                    ),
                ),
                (
                    "num_apartment",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número Depto"
                    ),
                ),
                (
                    "builded_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Año de Construcción"
                    ),
                ),
                (
                    "distribution",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Baño Visita", "Baño Visita"),
                            ("Hall", "Hall"),
                            ("Antejardin", "Antejardin"),
                            ("Patio de Servicio", "Patio de Servicio"),
                            ("Estar de Servicio", "Estar de Servicio"),
                            ("Jardin", "Jardin"),
                            ("Despensa", "Despensa"),
                            ("Sala Estar", "Sala Estar"),
                            ("Quincho", "Quincho"),
                            ("Lavadero Interior", "Lavadero Interior"),
                            ("Lavadero Exterior", "Lavadero Exterior"),
                            ("Escritorio", "Escritorio"),
                            ("Mansarda", "Mansarda"),
                            ("Terraza", "Terraza"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Espacios Adicionales",
                    ),
                ),
                (
                    "service",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Internet", "Internet"),
                            ("Luz", "Luz"),
                            ("Agua Potable", "Agua Potable"),
                            ("Alcantarillado", "Alcantarillado"),
                            ("Alarma", "Alarma"),
                            ("Telefono", "Telefono"),
                            ("Riego Automatico", "Riego Automatico"),
                            ("Porton Automatico", "Porton Automatico"),
                            ("TV Cable", "TV Cable"),
                            ("Chimenea", "Chimenea"),
                            ("Calefaccion", "Calefaccion"),
                            ("Aire Acondicionado", "Aire Acondicionado"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Servicios",
                    ),
                ),
                (
                    "kitchen",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Comedor Diario", "Comedor Diario"),
                            ("Cocina Equipada", "Cocina Equipada"),
                            ("Cocina Amoblada", "Cocina Amoblada"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Cocina",
                    ),
                ),
                (
                    "other",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Persianas", "Persianas"),
                            ("Protecciones Ventana", "Protecciones Ventana"),
                            ("Termopaneles", "Termopaneles"),
                            ("Jacuzzi", "Jacuzzi"),
                            ("Piscina", "Piscina"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Otros",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apartment",
                "verbose_name_plural": "Apartments",
                "ordering": ("-created",),
            },
        ),
    ]
