# Generated by Django 4.1.1 on 2023-12-28 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='realtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publications_realtor', to=settings.AUTH_USER_MODEL, verbose_name='Agente'),
        ),
    ]
