# Generated by Django 4.1.1 on 2023-02-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="views",
            field=models.ManyToManyField(
                related_name="publication_ip_visitor", to="properties.ipvisitor"
            ),
        ),
    ]
