# Generated by Django 4.1.1 on 2023-02-10 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Industrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "land_surface",
                    models.PositiveIntegerField(verbose_name="Superficie terreno (m²)"),
                ),
                (
                    "builded_surface",
                    models.PositiveIntegerField(
                        verbose_name="Superficie construida (m²)"
                    ),
                ),
                (
                    "num_offices",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Oficinas",
                    ),
                ),
                (
                    "num_local",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de Local"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industrials",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Industrial",
                "verbose_name_plural": "Industrials",
            },
        ),
        migrations.CreateModel(
            name="Cellar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "land_surface",
                    models.PositiveIntegerField(verbose_name="Superficie terreno (m²)"),
                ),
                (
                    "builded_surface",
                    models.PositiveIntegerField(
                        verbose_name="Superficie construida (m²)"
                    ),
                ),
                (
                    "num_offices",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Oficinas",
                    ),
                ),
                (
                    "num_local",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de Local"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cellars",
                        to="properties.property",
                    ),
                ),
            ],
            options={"verbose_name": "Cellar", "verbose_name_plural": "Cellars",},
        ),
    ]
