# Generated by Django 4.1.1 on 2023-02-25 02:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_publication_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationhistory",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de Creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operationhistory",
            name="modified",
            field=models.DateField(auto_now=True, verbose_name="Fecha de Modificaión"),
        ),
        migrations.AddField(
            model_name="operationhistory",
            name="state",
            field=models.BooleanField(default=True, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_images",
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="operation",
            field=models.CharField(
                choices=[
                    ("wa", "En espera"),
                    ("an", "No concretada"),
                    ("fi", "Concretada"),
                ],
                default="wa",
                max_length=2,
            ),
        ),
    ]
