# Generated by Django 4.1.1 on 2023-02-11 00:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_industrial_cellar"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellar",
            name="num_bathrooms",
            field=models.CharField(
                choices=[
                    ("", "Selecione una opción"),
                    ("0", "0"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                    ("14", "14"),
                    ("15", "15"),
                ],
                default=datetime.datetime(
                    2023, 2, 11, 0, 8, 43, 10322, tzinfo=datetime.timezone.utc
                ),
                max_length=2,
                verbose_name="Baños",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="industrial",
            name="num_bathrooms",
            field=models.CharField(
                choices=[
                    ("", "Selecione una opción"),
                    ("0", "0"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                    ("14", "14"),
                    ("15", "15"),
                ],
                default=datetime.datetime(
                    2023, 2, 11, 0, 8, 48, 18093, tzinfo=datetime.timezone.utc
                ),
                max_length=2,
                verbose_name="Baños",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parcel",
            name="electricity_feasibility",
            field=models.CharField(
                choices=[("si", "Si"), ("no", "No")],
                default=datetime.datetime(
                    2023, 2, 11, 0, 8, 52, 609970, tzinfo=datetime.timezone.utc
                ),
                max_length=2,
                verbose_name="Factibilidad Electricidad",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parcel",
            name="gas_feasibility",
            field=models.CharField(
                choices=[("si", "Si"), ("no", "No")],
                default=datetime.datetime(
                    2023, 2, 11, 0, 8, 56, 553195, tzinfo=datetime.timezone.utc
                ),
                max_length=2,
                verbose_name="Factibilidad Gas",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parcel",
            name="sewer_feasibility",
            field=models.CharField(
                choices=[("si", "Si"), ("no", "No")],
                default=datetime.datetime(
                    2023, 2, 11, 0, 9, 0, 993219, tzinfo=datetime.timezone.utc
                ),
                max_length=2,
                verbose_name="Factibilidad Alcantarillado",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parcel",
            name="water_feasibility",
            field=models.CharField(
                choices=[("si", "Si"), ("no", "No")],
                default=datetime.datetime(
                    2023, 2, 11, 0, 9, 6, 914298, tzinfo=datetime.timezone.utc
                ),
                max_length=2,
                verbose_name="Factibilidad Agua",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="urbansite",
            name="electricity_feasibility",
            field=models.CharField(
                choices=[("si", "Si"), ("no", "No")],
                default=datetime.datetime(
                    2023, 2, 11, 0, 9, 10, 258603, tzinfo=datetime.timezone.utc
                ),
                max_length=2,
                verbose_name="Factibilidad Electricidad",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="urbansite",
            name="gas_feasibility",
            field=models.CharField(
                choices=[("si", "Si"), ("no", "No")],
                default=datetime.datetime(
                    2023, 2, 11, 0, 9, 14, 251033, tzinfo=datetime.timezone.utc
                ),
                max_length=2,
                verbose_name="Factibilidad Gas",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="urbansite",
            name="sewer_feasibility",
            field=models.CharField(
                choices=[("si", "Si"), ("no", "No")],
                default=datetime.datetime(
                    2023, 2, 11, 0, 9, 20, 3391, tzinfo=datetime.timezone.utc
                ),
                max_length=2,
                verbose_name="Factibilidad Alcantarillado",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="urbansite",
            name="water_feasibility",
            field=models.CharField(
                choices=[("si", "Si"), ("no", "No")],
                default=datetime.datetime(
                    2023, 2, 11, 0, 9, 31, 98752, tzinfo=datetime.timezone.utc
                ),
                max_length=2,
                verbose_name="Factibilidad Agua",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "land_surface",
                    models.PositiveIntegerField(verbose_name="Superficie terreno (m²)"),
                ),
                (
                    "builded_surface",
                    models.PositiveIntegerField(
                        verbose_name="Superficie construida (m²)"
                    ),
                ),
                (
                    "num_bathrooms",
                    models.CharField(
                        choices=[
                            ("", "Selecione una opción"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                        ],
                        max_length=2,
                        verbose_name="Baños",
                    ),
                ),
                (
                    "num_local",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de Local"
                    ),
                ),
                (
                    "service",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Internet", "Internet"),
                            ("Luz", "Luz"),
                            ("Agua Potable", "Agua Potable"),
                            ("Alcantarillado", "Alcantarillado"),
                            ("Alarma", "Alarma"),
                            ("Telefono", "Telefono"),
                            ("TV Cable", "TV Cable"),
                            ("Chimenea", "Chimenea"),
                            ("Calefaccion", "Calefaccion"),
                            ("Aire Acondicionado", "Aire Acondicionado"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Servicios",
                    ),
                ),
                (
                    "kitchen",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Comedor Diario", "Comedor Diario"),
                            ("Cocina Equipada", "Cocina Equipada"),
                            ("Cocina Amoblada", "Cocina Amoblada"),
                        ],
                        default="",
                        max_length=250,
                        verbose_name="Cocina",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="properties.property",
                    ),
                ),
            ],
            options={"verbose_name": "Shop", "verbose_name_plural": "Shops",},
        ),
    ]
