# Generated by Django 4.1.1 on 2023-02-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0003_operationhistory_created_operationhistory_modified_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="operationhistory",
            name="codigo",
            field=models.CharField(blank=True, max_length=255, verbose_name="Codigo"),
        ),
        migrations.AddField(
            model_name="operationhistory",
            name="commune",
            field=models.CharField(blank=True, max_length=200, verbose_name="Comuna"),
        ),
        migrations.AddField(
            model_name="operationhistory",
            name="region",
            field=models.CharField(blank=True, max_length=200, verbose_name="Region"),
        ),
    ]
