# Generated by Django 4.1.1 on 2023-12-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_publication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='user',
        ),
    ]
