# Generated by Django 4.1.1 on 2023-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0004_operationhistory_codigo_operationhistory_commune_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationhistory",
            name="codigo",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Codigo"
            ),
        ),
        migrations.AlterField(
            model_name="operationhistory",
            name="commune",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Comuna"
            ),
        ),
        migrations.AlterField(
            model_name="operationhistory",
            name="region",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Region"
            ),
        ),
    ]
