# Generated by Django 4.1.1 on 2023-02-25 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_alter_operationhistory_codigo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationhistory",
            name="codigo",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 2, 25, 19, 15, 18, 776181, tzinfo=datetime.timezone.utc
                ),
                max_length=255,
                verbose_name="Codigo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="operationhistory",
            name="commune",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 2, 25, 19, 15, 22, 760434, tzinfo=datetime.timezone.utc
                ),
                max_length=200,
                verbose_name="Comuna",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="operationhistory",
            name="region",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 2, 25, 19, 15, 27, 838223, tzinfo=datetime.timezone.utc
                ),
                max_length=200,
                verbose_name="Region",
            ),
            preserve_default=False,
        ),
    ]
