# Generated by Django 4.1.1 on 2023-02-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_rename_num_enclosure_cellar_num_enclosures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="appraisal_value",
            field=models.PositiveIntegerField(null=True, verbose_name="Valor Tasación"),
        ),
        migrations.AlterField(
            model_name="property",
            name="commission_percentage",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Porcentaje Comisión",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="commission_value",
            field=models.PositiveIntegerField(verbose_name="Monto Comisión"),
        ),
    ]
