# Generated by Django 4.1.1 on 2023-02-25 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_alter_operationhistory_codigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationhistory",
            name="operation",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 2, 25, 21, 49, 21, 525048, tzinfo=datetime.timezone.utc
                ),
                max_length=50,
                verbose_name="Estado de Operación",
            ),
            preserve_default=False,
        ),
    ]
