# Generated by Django 4.1.1 on 2023-02-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_operationhistory_operation"),
    ]

    operations = [
        migrations.DeleteModel(name="OperationHistory",),
    ]
