# Generated by Django 4.1.1 on 2023-02-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0007_alter_property_appraisal_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="appraisal_value",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Valor Tasación"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="commission_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Porcentaje Comisión",
            ),
        ),
    ]
