# Generated by Django 4.1.1 on 2023-08-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_delete_operationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('pu', 'Publicado'), ('dr', 'No Publicado')], default='pu', max_length=3),
        ),
    ]
