# Generated by Django 4.1.1 on 2023-02-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_alter_property_appraisal_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IpVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                ("ip", models.CharField(max_length=100)),
            ],
            options={"abstract": False,},
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[("pu", "Publicado"), ("dr", "No Publicado")],
                default="dr",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="views",
            field=models.ManyToManyField(
                related_name="property_ip_visitor", to="properties.ipvisitor"
            ),
        ),
    ]
