# Generated by Django 4.1.1 on 2023-08-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_publication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='common_expenses',
            field=models.PositiveIntegerField(default=0, verbose_name='Gastos comunes'),
        ),
    ]
