# Generated by Django 4.1.1 on 2023-08-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_common_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='cellar',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='commune',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='house',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='industrial',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='ipvisitor',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='office',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='owner',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='property',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='propertycontact',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='publication',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='region',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='shop',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='urbansite',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
    ]
