# Generated by Django 4.1.1 on 2023-09-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_remove_publication_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='En Uso'),
        ),
    ]
