# Generated by Django 4.1.1 on 2023-09-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_publication_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='is_used',
        ),
    ]
