# Generated by Django 4.1.1 on 2023-12-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified', models.DateField(auto_now=True, verbose_name='Fecha de Modificaión')),
                ('deleted', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('rut', models.CharField(max_length=15, verbose_name='Rut')),
                ('phone', models.CharField(max_length=9, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=150, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('-created',),
            },
        ),
    ]
