# Generated by Django 4.1.1 on 2023-09-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-created',), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
