# Generated by Django 4.1.1 on 2023-12-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified', models.DateField(auto_now=True, verbose_name='Fecha de Modificaión')),
                ('deleted', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('from_email', models.EmailField(max_length=50, verbose_name='Email')),
                ('category', models.CharField(choices=[('', 'Seleccione una opción'), ('propietario', 'Propietario'), ('comprador', 'Comprador'), ('arrendatario', 'Arrendatario')], max_length=15, verbose_name='Categoria')),
                ('subject', models.CharField(max_length=50, verbose_name='Asunto')),
                ('phone', models.CharField(blank=True, max_length=9, verbose_name='Télefono(opcional)')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='OwnerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified', models.DateField(auto_now=True, verbose_name='Fecha de Modificaión')),
                ('deleted', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('from_email', models.EmailField(max_length=50, verbose_name='Email')),
                ('subject', models.CharField(choices=[('', 'Seleccione un tipo'), ('Venta', 'Venta'), ('Arriendo', 'Arriendo'), ('Arriendo Temporada', 'Arriendo Temporada'), ('Permuta', 'Permuta')], max_length=50, verbose_name='Asunto')),
                ('phone', models.CharField(blank=True, max_length=9, verbose_name='Télefono(opcional)')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'OwnerContact',
                'verbose_name_plural': 'OwnerContacts',
            },
        ),
    ]
