# Generated by Django 4.1.1 on 2023-02-11 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="category",
            field=models.CharField(
                choices=[
                    ("propietario", "Propetario"),
                    ("comprador", "Comprador"),
                    ("arrendatario", "Arrendatario"),
                ],
                default=datetime.datetime(
                    2023, 2, 11, 18, 15, 8, 578992, tzinfo=datetime.timezone.utc
                ),
                max_length=15,
                verbose_name="Categoria",
            ),
            preserve_default=False,
        ),
    ]
