# Generated by Django 4.1.1 on 2023-02-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_contact_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="category",
            field=models.CharField(
                choices=[
                    ("", "Seleccione una opción"),
                    ("propietario", "Propietario"),
                    ("comprador", "Comprador"),
                    ("arrendatario", "Arrendatario"),
                ],
                max_length=15,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=50, verbose_name="Asunto"),
        ),
    ]
