# Generated by Django 4.1.1 on 2023-09-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_contact_category_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='ownercontact',
            name='deleted',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
    ]
