# Generated by Django 4.1.1 on 2023-08-30 01:20

import apps.reports.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0011_alter_property_common_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationBuyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified', models.DateField(auto_now=True, verbose_name='Fecha de Modificaión')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purchase_sale_advance', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Anticipo de Compra/Venta')),
                ('purchase_sale_agreement', models.FileField(blank=True, null=True, upload_to=apps.reports.models.operation_buy_purchase_sale_files_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Promesa de Compra/Venta')),
                ('signature_purchase_sale_agreement', models.DateField(blank=True, null=True, verbose_name='Fecha Promesa de Compra/Venta')),
                ('sales_document', models.FileField(blank=True, null=True, upload_to=apps.reports.models.operation_buy_sales_document_files_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Compra/Venta')),
                ('sales_document_purchase_sale_agreement', models.DateField(blank=True, null=True, verbose_name='Fecha Compra/Venta')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total')),
                ('is_commission_paid', models.BooleanField(default=False, verbose_name='Comisión Pagada')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_buy_history', to='properties.publication')),
            ],
            options={
                'verbose_name': 'OperationBuyHistory',
                'verbose_name_plural': 'OperationsBuyHistory',
            },
        ),
    ]
