# Generated by Django 4.1.1 on 2023-02-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "modified",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificaión"
                    ),
                ),
                (
                    "type_property",
                    models.CharField(max_length=100, verbose_name="Tipo de Propiedad"),
                ),
                (
                    "operation",
                    models.CharField(max_length=50, verbose_name="Estado de Operación"),
                ),
                ("codigo", models.CharField(max_length=255, verbose_name="Codigo")),
                ("region", models.CharField(max_length=200, verbose_name="Region")),
                ("commune", models.CharField(max_length=200, verbose_name="Comuna")),
                ("total", models.CharField(max_length=100, verbose_name="Total")),
                (
                    "commission_percentage",
                    models.PositiveIntegerField(
                        verbose_name="Porcentaje Comisión(Valor Entero)"
                    ),
                ),
                ("commission_value", models.PositiveIntegerField()),
                (
                    "is_commission_paid",
                    models.BooleanField(default=False, verbose_name="Comisión Pagada"),
                ),
            ],
            options={
                "verbose_name": "OperationHistory",
                "verbose_name_plural": "OperationsHistory",
            },
        ),
    ]
