# Generated by Django 4.1.1 on 2023-08-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationbuyhistory',
            name='has_promise',
            field=models.BooleanField(default=False),
        ),
    ]
