# Generated by Django 4.1.1 on 2023-09-03 20:17

import apps.reports.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='operationrent',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='operationrent',
            name='guarantee_document',
            field=models.FileField(blank=True, null=True, upload_to=apps.reports.utils.operation_rent_guarantee_document_files_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documento de Garantia'),
        ),
        migrations.AlterField(
            model_name='operationrent',
            name='guarantee_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Valor de Garantia'),
        ),
        migrations.AlterField(
            model_name='operationrent',
            name='monthly_commission',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Comision'),
        ),
    ]
