# Generated by Django 4.1.1 on 2023-09-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_operationrent_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationrent',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
