# Generated by Django 4.1.1 on 2023-08-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_operationrent_operationbuyhistory_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationbuyhistory',
            old_name='sales_document_purchase_sale_agreement',
            new_name='signature_sales_document',
        ),
    ]
