# Generated by Django 4.1.1 on 2023-09-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_remove_publication_is_used'),
        ('reports', '0003_operationrent_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrent',
            options={'ordering': ('-payment_date',), 'verbose_name': 'PaymentRent', 'verbose_name_plural': 'PaymentRents'},
        ),
        migrations.AddField(
            model_name='operationbuyhistory',
            name='total_commission',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Comision'),
        ),
        migrations.AlterField(
            model_name='operationbuyhistory',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_buy', to='properties.publication'),
        ),
        migrations.AlterField(
            model_name='paymentrent',
            name='payment_date',
            field=models.DateField(verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='paymentrent',
            name='total_payment',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
    ]
