# Generated by Django 4.1.1 on 2023-08-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_sales_document_purchase_sale_agreement_operationbuyhistory_signature_sales_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationbuyhistory',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
