# Generated by Django 4.1.1 on 2023-09-15 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_options'),
        ('reports', '0006_alter_operationrent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationrent',
            options={'default_manager_name': 'objects', 'verbose_name': 'OperationRent', 'verbose_name_plural': 'OperationRents'},
        ),
        migrations.AlterModelManagers(
            name='operationrent',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='operationbuyhistory',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_buy', to='crm.client'),
        ),
        migrations.AddField(
            model_name='operationrent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_rent', to='crm.client'),
        ),
    ]
